<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;

class CustomerSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {


        $jayParsedAry = [
            [
                "customer_name" => "Devendra Tiwari",
                "phone" => 9415613449,
                "postcode" => 273001,
                "address" =>
                    "Block number 16, House number 202 - Phase 01, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ashok Kumar Yadav",
                "phone" => 9415173643,
                "postcode" => 273001,
                "address" =>
                    "Block number 01, House number 203 - Phase 01, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vidyadhar Gupta - Closed[20th  April]",
                "phone" => 9807865750,
                "postcode" => 273001,
                "address" =>
                    "Block number 31, House number 301 - Phase 02, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Shree Kant Gupta",
                "phone" => 9415313159,
                "postcode" => 273001,
                "address" =>
                    "Block number 16, House number 301 - Phase 01, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ravi Pratap Singh",
                "phone" => 6388797154,
                "postcode" => 273001,
                "address" =>
                    "Block number 21, House number 303 - Phase 01, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sant Kumar Sahi",
                "phone" => 9935737609,
                "postcode" => 273001,
                "address" =>
                    "Block number 30, House number 103 - Phase 02, Vasundhara Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vijay Pratap Singh",
                "phone" => 9415322699,
                "postcode" => 273001,
                "address" =>
                    "Block number 30, House number 301 - Phase 02, Vasundhara Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ajay Kumar Pandey",
                "phone" => 8299863293,
                "postcode" => 273001,
                "address" =>
                    "Block number 01, House number 202 - Phase 01, Vasundhara Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Amit Mishra Closed (23rd May)",
                "phone" => 7905274195,
                "postcode" => 273001,
                "address" =>
                    "Block 08, House number 301 Phase 01, Vasundhara Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ratish Kumar Singh",
                "phone" => 9005079785,
                "postcode" => 273001,
                "address" =>
                    "Block number 15, House number 303 - Phase 01, Vasundhara Taramndal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sanjeev Pandey - Closed[16th April]",
                "phone" => 8765195255,
                "postcode" => 273001,
                "address" => "Block number 26, House number 302 - Phase 02
Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Pranay Pratap Singh Closed(25th April)",
                "phone" => 9798891504,
                "postcode" => 273001,
                "address" =>
                    "Block number 27, House number 302 - Phase 02, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Guddu Gupta",
                "phone" => 8486922569,
                "postcode" => 273001,
                "address" => "Sector - 23, Sahjanwa - Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Manas Singh Closed(30th April)",
                "phone" => 9414888906,
                "postcode" => 273001,
                "address" =>
                    "Block number 31, House number 103 - Phase 01, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Shrishti Sharma closed (16th May)",
                "phone" => 8574007779,
                "postcode" => 273001,
                "address" =>
                    "Block number 30, House number 101 - Phase 02, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Neelam Singh closed(22nd April)",
                "phone" => 9555629198,
                "postcode" => 273001,
                "address" =>
                    "Block number 27, House number 301 - Phase 02, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ganesh Shanker Singh Closed(28th April)",
                "phone" => 9793305555,
                "postcode" => 273001,
                "address" =>
                    "Block number 23, House number 202 - Phase 01, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sunita Chand Closed (20th May)",
                "phone" => 9956558180,
                "postcode" => 273001,
                "address" => "Block Number-32
Room Number-104",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Kisan",
                "phone" => 9621687553,
                "postcode" => 273001,
                "address" => "Block Number-38
Room Number-303",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Pallavi",
                "phone" => 7565823457,
                "postcode" => 273001,
                "address" => "Block Number - 33
Room Number - 204",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Rajneesh Shrivastav closed(28th April)",
                "phone" => 9455790100,
                "postcode" => 273001,
                "address" =>
                    "Block number 03, House number 301 - Phase 01, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dharmendra Tiwari Closed(1st May)",
                "phone" => 9264965233,
                "postcode" => 273001,
                "address" =>
                    "Block number 04, House number 201 Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Archana Pandey Closed (6th May)",
                "phone" => 1111111110,
                "postcode" => 273001,
                "address" =>
                    "Block number 03, House number 202, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Richa Rai",
                "phone" => 9451189271,
                "postcode" => 273001,
                "address" =>
                    "Block number 31, House number 204, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vijay Kumar Gupta Closed (9th May)",
                "phone" => 9415824690,
                "postcode" => 273001,
                "address" =>
                    "H NO-C178/119H, NEAR DR. MANISHA SHAHI LANE, MOHALLA -DAUDPUR GORAKHPUR",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Naincy",
                "phone" => 8317068536,
                "postcode" => 273001,
                "address" =>
                    "Block number 18, House number 304, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sona Gosawami Closed Account (11th May)",
                "phone" => 9415270945,
                "postcode" => 273001,
                "address" =>
                    "Block number 31, House number 203-Phase 2, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Soni Kumari Closed(7th May )",
                "phone" => 2222222222,
                "postcode" => 110096,
                "address" =>
                    "Block number 21, House no 104,  Vasundhara enclave Taramandal, Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "M.M Tripathi",
                "phone" => 9415828403,
                "postcode" => 273016,
                "address" =>
                    "Block number 20, House number 203, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Chandra Sekhar Yadav Closed (26th May)",
                "phone" => 7355117129,
                "postcode" => 273016,
                "address" =>
                    "Block number 19, House number 102, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Mukesh Kumar",
                "phone" => 9432414879,
                "postcode" => 273016,
                "address" =>
                    "Block Number 28,House Number-204, Vasundhara Enclave Taramandal , Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Rambha Shukla Closed (23rd May)",
                "phone" => 9140866938,
                "postcode" => 273016,
                "address" =>
                    "Block Number 28, House Number-104, Vasundhara Enclave Taramandal , Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Yogendra",
                "phone" => 9839083119,
                "postcode" => 273016,
                "address" =>
                    "Block number 38, House number 201 - Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Mohan Sharma Closed (23rd May)",
                "phone" => 8630496833,
                "postcode" => 273016,
                "address" =>
                    "Block number 29, House number 201, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "SK Mishra",
                "phone" => 8419054444,
                "postcode" => 273016,
                "address" =>
                    "Block number 10, House number 101, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Satendra Singh Closed (31st May)",
                "phone" => 9793514225,
                "postcode" => 273016,
                "address" =>
                    "Block number 36, House number 104, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sanjay Goswal",
                "phone" => 9215774480,
                "postcode" => 273016,
                "address" =>
                    "Block number 35, House number 102, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ishita Shahi",
                "phone" => 8400876767,
                "postcode" => 273016,
                "address" => "HIG-55 Siddharth Puram Vister",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Rajvansh",
                "phone" => 7905798349,
                "postcode" => 111111,
                "address" => "HIB A-337, Near Bharat Marbels",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Aditya Thakurai",
                "phone" => 8840501097,
                "postcode" => 111111,
                "address" => "LIG-34,35,Siddharth Puram enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "SS Mishra",
                "phone" => 9450110088,
                "postcode" => 111111,
                "address" =>
                    "Block number 11, House number 101, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Uma  Nigam",
                "phone" => 9264976530,
                "postcode" => 111111,
                "address" => "HIG-2nd, House No-5, Siddharth Puram Vaster",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Shishir Tripathi Closed (23rd May)",
                "phone" => 8840370805,
                "postcode" => 111111,
                "address" => "MIG-249, Siddharth Puram Vaster Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Amarjeet Yadav",
                "phone" => 8318762586,
                "postcode" => 111111,
                "address" => "Beside Vasundra Shiv Hanuman Mandir",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Padmakar Tripathi Closed (10th July)",
                "phone" => 7905894473,
                "postcode" => 111111,
                "address" => "Block number 28, House number 101",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Som Shankar Dubey",
                "phone" => 9885409389,
                "postcode" => 111111,
                "address" => "HIG-510, Near Sawnanth Senior",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Amit Pandey",
                "phone" => 8858536901,
                "postcode" => 273016,
                "address" => "Beside Vasundhra",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dr Priyanka Singh Closed (23rd May)",
                "phone" => 9838704446,
                "postcode" => 273016,
                "address" =>
                    "Block number 29, House number 202, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Deep Narayan Yadav",
                "phone" => 9818205550,
                "postcode" => 273016,
                "address" => "HIG - 14 Near Waterwyas Restaurant",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Rajneesh Kumar Dubey",
                "phone" => 9794881668,
                "postcode" => 111111,
                "address" =>
                    "HIG-5-13 Siddharth Puram Taramandal Gorakhpur Near Spancer",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Santosh Singh",
                "phone" => 9838957844,
                "postcode" => 111111,
                "address" => "HIG-36, Near Bharat Marble Taramandal, Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ranvijay Vishwkarma",
                "phone" => 9415212256,
                "postcode" => 111111,
                "address" => "HIG-C-320, Near Lack View, Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Krishnamani Ojha",
                "phone" => 9936885905,
                "postcode" => 111111,
                "address" => "MIG-270, Near Bata Taramandal,Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ranjeet Mandwal Closed (24th May)",
                "phone" => 9670131328,
                "postcode" => 111111,
                "address" => "Riya Beauty Parlour Near Neya Bhagat Chauraha",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Neeraj Sharma",
                "phone" => 8901722242,
                "postcode" => 111111,
                "address" => "HIG-3/21",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Saumya Tripathi",
                "phone" => 8802013132,
                "postcode" => 111111,
                "address" => "Opposite GDA Office",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Piyush Koshik",
                "phone" => 8318587900,
                "postcode" => 111111,
                "address" => "Lack View C-206",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ankur Mishra",
                "phone" => 9795979899,
                "postcode" => 111111,
                "address" => "A.D Opposite Surmount Gali",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ravi Singh",
                "phone" => 3333333333,
                "postcode" => 111111,
                "address" => "A.D Opposite Surmount Gali",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ravi Sharma Closed (10th June)",
                "phone" => 8795092009,
                "postcode" => 111111,
                "address" => "Flat No. 208, Block 02 - Lakeview Apartment 
Taramandal ,Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sonu Singh Closed (10th May)",
                "phone" => 4444444444,
                "postcode" => 111111,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sunita Singh",
                "phone" => 9807869079,
                "postcode" => 111111,
                "address" => "Block C, Flat - 406, Lack View Taramandal",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dr Gaurav  Sarin",
                "phone" => 9565453524,
                "postcode" => 111111,
                "address" => "Taramandal",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Amit Singh",
                "phone" => 5555555555,
                "postcode" => 111111,
                "address" => "Bloack-3, Flat-103 , Taramandal",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sanjay Sukla",
                "phone" => 9918104000,
                "postcode" => 111111,
                "address" => "Lock View Block A, Flat-406",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Faraz Khan",
                "phone" => 9125555559,
                "postcode" => 111111,
                "address" => "Suraj Kund",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Rakesh Kumar Singh",
                "phone" => 9935904084,
                "postcode" => 111111,
                "address" => "177/P Sushila Aavaas Jail Road Gita Vatika G.K.D",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Adarsh Gupta",
                "phone" => 9044489291,
                "postcode" => 111111,
                "address" => "Rav Gym",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Mrityunjay Kumar Mishra",
                "phone" => 9452843085,
                "postcode" => 111111,
                "address" => "Lack View AD Block C, Flat-102",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Raghav Kushwah",
                "phone" => 9305499262,
                "postcode" => 111111,
                "address" => "Block-C, Flat-106",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Raj Kumar Shukla",
                "phone" => 9838502486,
                "postcode" => 111111,
                "address" => "MIG-206, Near Bata",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Harsh",
                "phone" => 7007235425,
                "postcode" => 111111,
                "address" => "124 Chote Kajipur G.K.D",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Govind Kumar Maurya",
                "phone" => 8574121830,
                "postcode" => 111111,
                "address" => "Paidakganj Near Railway Caloni",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vikas",
                "phone" => 9651917347,
                "postcode" => 111111,
                "address" => "Rav Gym",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Avinash Singh",
                "phone" => 6666666666,
                "postcode" => 111111,
                "address" => "House No -49,Vaishali Taramandal G.D.A",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "R.N Singh",
                "phone" => 9839886688,
                "postcode" => 111111,
                "address" => "3/402 ,Vashundhra Phase 3rd",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sandeep Prjapati",
                "phone" => 9650185647,
                "postcode" => 111111,
                "address" => "Opposite G.D.A",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sadhana",
                "phone" => 7007450451,
                "postcode" => 111111,
                "address" => "Near Champa Devi Park, Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Durgesh Chandravansi",
                "phone" => 9721518018,
                "postcode" => 111111,
                "address" => "Near Siyaram Library, Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Modern Diagnostic Center",
                "phone" => 7777777771,
                "postcode" => 111111,
                "address" => "Opposite Hanuman Temple Betihata,
Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ankur Singh",
                "phone" => 7007441744,
                "postcode" => 111111,
                "address" => "Rav Gym, Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ankur Sankar Closed (8th June)",
                "phone" => 8318958878,
                "postcode" => 111111,
                "address" => "Rav Gym",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Hariom Yadav Closed (8th June)",
                "phone" => 7052255077,
                "postcode" => 111111,
                "address" => "Rav Gym",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Shivam Chauhdhary",
                "phone" => 7777777777,
                "postcode" => 111111,
                "address" => "Rav Gym",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vishnu",
                "phone" => 9958334078,
                "postcode" => 111111,
                "address" => "Rav Gym",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Aswani Maurya",
                "phone" => 9628768852,
                "postcode" => 111111,
                "address" => "Rav Gym",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Saurabh Singh",
                "phone" => 9792066666,
                "postcode" => 111111,
                "address" => "Rav Gym",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dharampal Yadvanshi",
                "phone" => 1111111111,
                "postcode" => 111111,
                "address" => "Taramandal",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Mudit Closed (9th June)",
                "phone" => 8299364069,
                "postcode" => 111111,
                "address" => "Shop",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Chaman Closed (9th June)",
                "phone" => 8417808061,
                "postcode" => 111111,
                "address" => "Shop",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Gorakh Singh Closed (9th June)",
                "phone" => 9838120142,
                "postcode" => 111111,
                "address" => "Lack View, Block- C, Flat-507",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sadanand Pandey",
                "phone" => 9936467075,
                "postcode" => 111111,
                "address" => "MIG-118",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ajay Pandey",
                "phone" => 7753983742,
                "postcode" => 111111,
                "address" => "MIG-55",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Amar Nath Ojha",
                "phone" => 9936474499,
                "postcode" => 111111,
                "address" => "MIG-65,Siddharth Enclave",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Amit Dubey Closed (28th June)",
                "phone" => 7408557979,
                "postcode" => 111111,
                "address" => "Room No-102, Care of Santosh Singh",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Suman Sharma Closed (30th June)",
                "phone" => 6387467162,
                "postcode" => 111111,
                "address" => "Room No-103, Care of Santosh Singh",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Alok Pandey",
                "phone" => 8709608457,
                "postcode" => 111111,
                "address" => "MIG-55",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vaibhav Pandey",
                "phone" => 9151708975,
                "postcode" => 111111,
                "address" => "MIG-75",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Devansh Yadav",
                "phone" => 9044096616,
                "postcode" => 111111,
                "address" =>
                    "Block number 15, House number 304 - Phase 01, Vasundhara enclave Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Shailesh Singh",
                "phone" => 8510092255,
                "postcode" => 111111,
                "address" => "Opposite GDA",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Anil Kumar Gupta",
                "phone" => 9305732496,
                "postcode" => 111111,
                "address" => "Side Of Bharat Marbal",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ajay Pratap Singh",
                "phone" => 9453649612,
                "postcode" => 111111,
                "address" => "Flat no-335-D",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Deepa Gupta",
                "phone" => 9140659801,
                "postcode" => 111111,
                "address" => "Flat No-A-51-J(338)",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ashutosh Srivastva",
                "phone" => 7880401601,
                "postcode" => 111111,
                "address" => "Msar Childiy Ghar",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Chandrabali Yadav",
                "phone" => 8896289825,
                "postcode" => 111111,
                "address" => "Front of GA Office",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Abheejit Closed (24th June)",
                "phone" => 8932000012,
                "postcode" => 111111,
                "address" => "Lahiya Near Chidiyaghar,
 Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dhanraj Singh",
                "phone" => 9919012999,
                "postcode" => 111111,
                "address" => "MIG-25-A,
Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Krishan Pal Singh",
                "phone" => 9453728811,
                "postcode" => 111111,
                "address" => "MIG-27,
Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sunita agarval",
                "phone" => 9336404533,
                "postcode" => 111111,
                "address" => "Gardeniya Flat-106,
Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dr. Roop Kumar",
                "phone" => 8299698633,
                "postcode" => 111111,
                "address" => "Block-06, LIC Office
Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Rajendra Aggarwal",
                "phone" => 1111111112,
                "postcode" => 111111,
                "address" => "Gemini Gardeniya, Flat-101,
Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vishal",
                "phone" => 1111111113,
                "postcode" => 111111,
                "address" => "Not Given",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Umang",
                "phone" => 1111111114,
                "postcode" => 111111,
                "address" => "House no 34, Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "SK Singh",
                "phone" => 1111111115,
                "postcode" => 111111,
                "address" => "Block number 28, House number 301,
Vasundhara enclave taramandal gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Kanchan Sharma",
                "phone" => 8299287634,
                "postcode" => 111111,
                "address" =>
                    "H.No-9, Siddharthpurum Extension, Bharat Marble Wali Gali.",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sameer  Singh",
                "phone" => 1111111116,
                "postcode" => 111111,
                "address" => "Hig24 ,Taramandal",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Hansnath Pandey",
                "phone" => 1111111117,
                "postcode" => 111111,
                "address" => "Block 1,House No-303",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Rk yadav",
                "phone" => 1111111118,
                "postcode" => 111111,
                "address" => "block 10 flait 302 vasundhara",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ritesh jain",
                "phone" => 1111111119,
                "postcode" => 111111,
                "address" => "hig-2nd house no 5 near surmount",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ram kumar",
                "phone" => 1111111120,
                "postcode" => 111111,
                "address" => "Near by Manya collection Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Arhan khan",
                "phone" => 1111111121,
                "postcode" => 111111,
                "address" => "rao gym taramandal",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Darshika singh",
                "phone" => 1111111122,
                "postcode" => 111111,
                "address" => "block 3 flait 105 lack view taramandal",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Mamta Dubey",
                "phone" => 1111111123,
                "postcode" => 111111,
                "address" => "Block 36 Flat No -301 Vashundhara",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ruchi A/C Closed",
                "phone" => 1111111124,
                "postcode" => 111111,
                "address" => "block 10 flait  303 vasundhra",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Jaidev Singh",
                "phone" => 1111111125,
                "postcode" => 111111,
                "address" => "Opposite GDA office",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Brijbhusan mishra",
                "phone" => 1111111126,
                "postcode" => 273016,
                "address" => "opposite gda office",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vikash Pandey",
                "phone" => 1111111127,
                "postcode" => 273017,
                "address" => "Block-31,House No.-103,Vasundhara",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Neha Tripathi",
                "phone" => 1111111128,
                "postcode" => 273017,
                "address" => "opposite gda office",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Atul Srivastava",
                "phone" => 1111111129,
                "postcode" => 273016,
                "address" => "Msar Chidiya Ghar",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vivek Singh",
                "phone" => 1111111130,
                "postcode" => 273016,
                "address" => "Block-35 , House No-103 Vasundhara",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Arun",
                "phone" => 1111111131,
                "postcode" => 111111,
                "address" => "Block 10 Flait no 202 vasundhra",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "sanjay kumar singh",
                "phone" => 1111111132,
                "postcode" => 111111,
                "address" => "block 07 flait no 303 vasundhra",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Savita singh",
                "phone" => 1111111133,
                "postcode" => 273016,
                "address" => "opposite gda office",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Rajesh singh",
                "phone" => 1111111134,
                "postcode" => 273016,
                "address" => "near rav gym",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Suresh  singh",
                "phone" => 1111111135,
                "postcode" => 273016,
                "address" => "HIG A/10Gautam vistar",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dr Ravi Shankar Singh",
                "phone" => 1111111136,
                "postcode" => 273016,
                "address" => "HIG -II-40",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "CA Jugunu dubey",
                "phone" => 1111111137,
                "postcode" => 273016,
                "address" => "near bhagat chauraha",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "chaurasiya ji",
                "phone" => 1111111138,
                "postcode" => 273016,
                "address" => "flait no 1402 Amaravati nikunj",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Bhanu Pratap Singh",
                "phone" => 1111111139,
                "postcode" => 273016,
                "address" => "Near Nauka Vihar",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Guddu chaubey",
                "phone" => 1111111140,
                "postcode" => 111111,
                "address" => "block 01 flait no 201 vasundra fase 3",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Kamlesh Chandra Tripathi",
                "phone" => 1111111141,
                "postcode" => 273016,
                "address" => "Childiya Ghar, Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sk Tripathi",
                "phone" => 1111111142,
                "postcode" => 273016,
                "address" => "&quot;Block number 38, House number 304 - Phase 02,
Vasundhara enclave taramandal gorakhpur&quot;",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dr. AN Singh",
                "phone" => 1111111143,
                "postcode" => 273016,
                "address" => "In Front of Vasundhara",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ankur Ji",
                "phone" => 1111111144,
                "postcode" => 273016,
                "address" => "Behind Majestic clinic",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Kameshwar Singh Ac/Closed 4/1/24",
                "phone" => 1111111145,
                "postcode" => 273017,
                "address" => "opposite gda office",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Shiv kumar dubey",
                "phone" => 1111111146,
                "postcode" => 273017,
                "address" => "Near Baudh Sangrahalaya",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Reshu Rana",
                "phone" => 1111111147,
                "postcode" => 273016,
                "address" => "In front of lake View",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ram Narayan Yadav",
                "phone" => 1111111148,
                "postcode" => 273017,
                "address" => "Near Baudh Sangrahalaya",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ram Pratap Rai",
                "phone" => 1111111149,
                "postcode" => 273017,
                "address" => "Near Baudh Sangrahalaya",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vaibhav Rai",
                "phone" => 1111111150,
                "postcode" => 273017,
                "address" => "Yashodhara R-201",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Shikha Jaiswal",
                "phone" => 1111111151,
                "postcode" => 273016,
                "address" => "Bharwalia Bujurg",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Himanshu Tripathi",
                "phone" => 1111111152,
                "postcode" => 273017,
                "address" => "Lake View Coloney",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Shailendra Singh",
                "phone" => 1111111153,
                "postcode" => 273017,
                "address" => "Yashodhara R-9",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Arvind Singh",
                "phone" => 1111111154,
                "postcode" => 273017,
                "address" => "Block-21, Flat-304",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Jagdish Pratap Singh",
                "phone" => 1111111155,
                "postcode" => 273016,
                "address" => "In front of Lake view",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sheshnath",
                "phone" => 1111111156,
                "postcode" => 273017,
                "address" => "Near Mount Litra School",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "S V Singh",
                "phone" => 1111111157,
                "postcode" => 273017,
                "address" => "Chidiya Ghar Lohiya Colony",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vaibhav Shahi",
                "phone" => 1111111158,
                "postcode" => 273017,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Rekha Singh",
                "phone" => 1111111159,
                "postcode" => 111111,
                "address" => "Vaishali Colony",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Nand Kishor Sahni",
                "phone" => 1111111160,
                "postcode" => 273016,
                "address" => "Vaishali Colony",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sumit Singh",
                "phone" => 1111111161,
                "postcode" => 273017,
                "address" => "House No-1116, Gemini",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Matadin Singh",
                "phone" => 1111111162,
                "postcode" => 273017,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Matadin Singh Tenant",
                "phone" => 1111111163,
                "postcode" => 273016,
                "address" => "opposite gda office",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Akhileshwar Dubey",
                "phone" => 1111111164,
                "postcode" => 273016,
                "address" => "MIG-238",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Satendra Tripathi",
                "phone" => 1111111165,
                "postcode" => 273016,
                "address" => "Block-3, house No.-108,Lake View",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Kajal Thakurai",
                "phone" => 1111111166,
                "postcode" => 273016,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Himanshu Kumar",
                "phone" => 1111111167,
                "postcode" => 273016,
                "address" => "MIG -145 , Near Amarawati",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "DC  SIR",
                "phone" => 1111111168,
                "postcode" => 111111,
                "address" => "Near by Bombay Security",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Bipul Gupta",
                "phone" => 1111111169,
                "postcode" => 273016,
                "address" => "Near Canara Bank Taramandal Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Arvind Shukla",
                "phone" => 1111111170,
                "postcode" => 273016,
                "address" => "Kailash Colony Bhagat Chouraha Ganpati marriage Hall",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vikash Jaiswal",
                "phone" => 1111111171,
                "postcode" => 273016,
                "address" => "Near  Gemini Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "krishan Mohan",
                "phone" => 1111111172,
                "postcode" => 111111,
                "address" => "Near Surmount Schoool Gol Park",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sudha Singh",
                "phone" => 1111111173,
                "postcode" => 273016,
                "address" => "Lake View Block 3,Flat No.-107",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ashutosh  Chandra",
                "phone" => 1111111174,
                "postcode" => 273017,
                "address" => "Near Surmount School  Gol Park",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dewakar Singh",
                "phone" => 1111111175,
                "postcode" => 273016,
                "address" => "Azad  Chouk",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Prince Yadav",
                "phone" => 1111111176,
                "postcode" => 273017,
                "address" => "Block-36 Flat No-302",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Matadin Singh Tenant 2",
                "phone" => 1111111177,
                "postcode" => 273016,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Amita Tripathi",
                "phone" => 1111111178,
                "postcode" => 273016,
                "address" => "Near GDA",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Shiv Kumar",
                "phone" => 1111111179,
                "postcode" => 273016,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Shubham Singh",
                "phone" => 1111111180,
                "postcode" => 273016,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "S S YAdav",
                "phone" => 1111111181,
                "postcode" => 273016,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Pramod Chaturvedi",
                "phone" => 1111111182,
                "postcode" => 273017,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dr.Rajkumar Singh",
                "phone" => 1111111183,
                "postcode" => 273017,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Bhagirathi",
                "phone" => 1111111184,
                "postcode" => 273016,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Dr. Dwarikanath",
                "phone" => 1111111185,
                "postcode" => 273016,
                "address" => "Taramandal",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Punam Rai",
                "phone" => 1111111186,
                "postcode" => 273016,
                "address" => "HIG-C-11",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Nikhil Tripathi",
                "phone" => 1111111187,
                "postcode" => 273016,
                "address" => "Near GDA",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Jawad Ahmad",
                "phone" => 1111111188,
                "postcode" => 273016,
                "address" => "Block-I , House No.-6",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ramesh Bahadur Singh",
                "phone" => 1111111189,
                "postcode" => 273016,
                "address" => "Block-3, Flat No-405/C ,Lake view",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vivek Singh Gautam Vihar",
                "phone" => 1111111190,
                "postcode" => 273016,
                "address" => "Gautam Vihar In front Of Park",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "JP Singh",
                "phone" => 1111111191,
                "postcode" => 273016,
                "address" => "Near Spencer bazar",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Rajesh Kumar Rao",
                "phone" => 1111111192,
                "postcode" => 111111,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sujeet Singh",
                "phone" => 1111111193,
                "postcode" => 111111,
                "address" => "Nar spencer",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "DN Tiwari",
                "phone" => 1111111194,
                "postcode" => 111111,
                "address" => "Behind Majestic Clinic India",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sagar",
                "phone" => 1111111195,
                "postcode" => 273016,
                "address" => "HIG-107",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Manish Kumar Singh",
                "phone" => 1111111196,
                "postcode" => 273016,
                "address" => "MIG-271 Taramandal",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ramagya",
                "phone" => 1111111197,
                "postcode" => 111111,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Preeti Shukla",
                "phone" => 1111111198,
                "postcode" => 273016,
                "address" => "Block-1 , Flat No.- 204",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Golu Gupta",
                "phone" => 1111111199,
                "postcode" => 273016,
                "address" => "New Shivpuri Colony Near Ambedkar Park",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ajeet Kumar Singh",
                "phone" => 1111111200,
                "postcode" => 273016,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Sahwat Pandey",
                "phone" => 1111111201,
                "postcode" => 273016,
                "address" => "Near Spencer Shop",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Deepa Sharma",
                "phone" => 1111111202,
                "postcode" => 273017,
                "address" => "HIG-15",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Supriya Nitish Rai",
                "phone" => 1111111203,
                "postcode" => 273017,
                "address" => "Sattashi House,opposite GDA Office",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "New customer start 6/1/24",
                "phone" => 1111111204,
                "postcode" => 111111,
                "address" => "HIG-15",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Manoj",
                "phone" => 1111111205,
                "postcode" => 111111,
                "address" => "Gorakhpur",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vicky Gupta",
                "phone" => 1111111206,
                "postcode" => 111111,
                "address" => "Opposite Vashundhara Gate(Tee Shop)",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Vicky(Vishal)",
                "phone" => 1111111207,
                "postcode" => 111111,
                "address" => "Indranagar Near, Shakuntala Marriage Hall",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Ruchi Rai",
                "phone" => 1111111208,
                "postcode" => 273017,
                "address" => "Block-5,Flat no.-304, Vashundhara",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
            [
                "customer_name" => "Amlesh Pandey",
                "phone" => 1111111209,
                "postcode" => 273017,
                "address" => "Block -35, Flat No-303 Vashundhara",
                "status" => 1,
                "state" => "Uttar Pradesh",
                "city" => "Gorakhpur",
            ],
        ];

        foreach ($jayParsedAry as $item) {

            $user = \App\Models\User::create([
                'name' => $item['customer_name'],
                'email'=> $item['phone']."@milkmilch.com",
                'password'=> Hash::make('milkmilch123'),
                'phone' => $item['phone'],
                'address' => $item['address'],
                'city' => $item['city'],
                'state' => $item['state'],
                'postal_code' => $item['postcode'],
                'role_id' => 5,
                'status' =>1
            ]);
            \App\Models\Customer::create(['user_id' => $user->id]);
        }

    }
}
